# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = 'https://savingourselvesfordeath.com/'
defaultContentLanguage = "en"
title = 'Saving Ourselves For Death Masters Ultimate'

[imaging]
  anchor = 'Center'